services:
  
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  db_test:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${TEST_DB}
    ports:
      - "5433:5432"   # окремий порт
    command: ["postgres"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default
    deploy:
      replicas: 0    # тільки для CI/CD, не піднімаємо постійно
    
 # === Backend (FastAPI) ===
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${BACKEND_PORT}:8000"

  # === Frontend (React/Vite) ===
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend

   # === Landing (Next.js) ===
  landing:
    build:
      context: ./landing
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - "${LANDING_PORT}:3001"
      
volumes:
  db_data: